import React, { useState } from "react";
import SelectTrainer from "./SelectTrainer";
import StartChat from "./StartChat";

const MotivateHome = () => {
    const [showTrainer, setShowTrainer] = useState(true);
    const [selectedTrainer, setSelectedTrainer] = useState(null);

    const goBackToSelectTrainer = () => {
        setShowTrainer(true);
      };
      

    return (
        <div className="flex flex-col items-center bg-gradient-to-r from-teal-500 to-teal-700
        p-8 rounded-lg shadow-2xl w-full text-s text-white my-4 mx-auto sm:w-3/4 lg:w-1/2">
        <div className="h1 flex justify-center items-center w-10 h-10 border-0 rounded-full bg-teal-800 text-white text-xl">
          <i className="fa-solid fa-dumbbell"></i>
        </div>
    <h2 className="my-8 h2 text-3xl uppercase text-shadow flex text-teal-100">MotivateMe</h2>
        {showTrainer ? (
                <SelectTrainer onTrainerSelected={(trainer) => {
                    setSelectedTrainer(trainer);
                    setShowTrainer(false);
                }} />
            ) : (
                <StartChat selectedTrainer={selectedTrainer} goBack={goBackToSelectTrainer} />
            )}

            <p className="mt-8 text-justify italic">This AI tool is intended for informational purposes only and should not be considered a substitute for professional advice. While the AI-generated content strives to provide accurate and helpful information, it may not always be perfect or completely up-to-date. Users are encouraged to independently verify any information provided by this tool and consult with qualified professionals for specific advice tailored to their individual needs. The creators of this AI tool disclaim any liability for errors, omissions, or damages arising from the use or reliance on the information generated by this tool. By using <span className="text-green-900 font-bold">MotivateMe</span>, you acknowledge and accept these terms of use.</p>
        </div>
    );
};

export default MotivateHome
