import React, { useState } from "react";
import SelectTrainer from "./SelectTrainer";
import StartChat from "./StartChat";
import SubSiteHeader from "../WebsiteComponents/SubSiteHeader"

const MotivateHome = () => {
    const [showTrainer, setShowTrainer] = useState(true);
    const [selectedTrainer, setSelectedTrainer] = useState(null);

    const goBackToSelectTrainer = () => {
        setShowTrainer(true);
      };
      

    return (
<div className="bg-gradient-to-r from-teal-500 to-teal-700 p-8 shadow-2xl w-full text-s text-white flex flex-col items-center justify-center sm:my-4 sm:rounded-lg mx-auto sm:w-3/4 lg:w-1/2">
<SubSiteHeader name={location.pathname}/>
        {showTrainer ? (
                <SelectTrainer onTrainerSelected={(trainer) => {
                    setSelectedTrainer(trainer);
                    setShowTrainer(false);
                }} />
            ) : (
                <StartChat selectedTrainer={selectedTrainer} goBack={goBackToSelectTrainer} />
            )}

            <p className="mt-8 text-justify italic">This AI tool is intended for informational purposes only and should not be considered a substitute for professional advice. While the AI-generated content strives to provide accurate and helpful information, it may not always be perfect or completely up-to-date. Users are encouraged to independently verify any information provided by this tool and consult with qualified professionals for specific advice tailored to their individual needs. The creators of this AI tool disclaim any liability for errors, omissions, or damages arising from the use or reliance on the information generated by this tool. By using <span className="text-green-900 font-bold">MotivateMe</span>, you acknowledge and accept these terms of use.</p>
        </div>
    );
};

export default MotivateHome
